# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.112

automation: !include automations.yaml
climate: !include_dir_list /config/include/integrations/climate/
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
rest: !include rest.yaml
sensor: !include sensors.yaml
template: !include template_sensors.yaml

camera:
  - platform: local_file
    name: Doorbell snapshot
    file_path: /media/local/g4_doorbell_snapshot.jpg

media_source:

notify:  
  - platform: group
    name: all_ios_devices
    services:
    - service: mobile_app_iphone_van_sietse
    - service: mobile_app_iphone_van_femke

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_translate_say

lovelace: !include /config/include/configuration/lovelace.yaml
frontend:
  themes: !include_dir_merge_named /config/include/lovelace/00_general/03_themes