# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.112

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
rest: !include rest.yaml
sensor: !include sensors.yaml
template: !include template_sensors.yaml

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
  - platform: local_file
    name: Doorbell snapshot
    file_path: /media/local/g4_doorbell_snapshot.jpg

media_source:

notify:  
  - platform: group
    name: all_ios_devices
    services:
    - service: mobile_app_iphone_van_sietse
    - service: mobile_app_iphone_van_femke

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_translate_say

lovelace: !include /config/include/configuration/lovelace.yaml