- platform: afvalwijzer
  provider: mijnafvalwijzer
  postal_code: !secret postal_code
  street_number: !secret house_number 
  exclude_pickup_today: false
  default_label: Geen

- platform: nordpool
  VAT: False
  currency: "EUR"
  price_in_cents: false
  low_price_cutoff: 0.9
  region: "NL"
  precision: 3
  price_type: kWh
  additional_costs: >
    {% set VAT = 0.21 %}
    {% set tax_kWh = 0.12599 %}
    {% set opslag = 0.018 %} {# Tibber, ex. BTW #}
    {{ (current_price * VAT ) + (tax_kWh + opslag) * (1 + VAT)|float }}

- platform: template
  sensors:
    iemand_thuis:
      friendly_name: Iemand thuis
      icon_template: >-
        {% if is_state('binary_sensor.iemand_thuis','on') %}
          mdi:home-account
        {% else %}
          mdi:home-outline
        {% endif %}
      value_template: >-
        {% if is_state('person.sietse','home') or is_state('person.femke','home') %}
        on
        {% else %}
        off
        {% endif %}

# - platform: derivative
#   name: 'Energy use per hour'
#   source: sensor.dagverbruik_energie